---
name: Branch Protection

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  protect-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: infamous-riddles/branch-guardian@v1
        with: 
          PERSONAL-ACCESS-TOKEN: ${{ secrets.PAT }}
          BASE-BRANCH-PATTERN: 'master'
          REQUIRED-NUMBER-OF-REVIEWERS: 2
          REQUIRED-STATUS-CHECKS: 'build,test'
          REQUIRE-REVIEW-FROM-CODEOWNERS: 'true'
          DISMISS-STALE-PR-APPROVALS-ON-NEW-COMMITS: 'true'
          REQUIRE-LINEAR-HISTORY: 'true'
          ALLOW-FORCE-PUSHES: 'true'
          ALLOW-DELETIONS: 'true'
          INCLUDE-ADMINISTRATORS: 'true'
          # List of users allowed to push on the protected branch.
          # RESTRICTIONS-USERS: 'rathan71'
          # # List of teams allowed to push on the protected branch.
          # RESTRICTIONS-TEAMS: 'rathan71'
