name: Pipeline B

on:
  workflow_run:
    workflows: ["Pipeline A"]
    types:
      - completed

jobs:
  validate_output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: output

      - name: Validate Output
        run: |
          # Read and validate the output
          output_data=$(cat output/output.txt)
          if [ "$output_data" == "Hello, World!" ]; then
            echo "Validation successful"
          else
            echo "Validation failed"
            exit 1
          fi
