name: Terraform Cloud Apply Run

on:
  pull_request:
    branches:
    ## RECOMMENDED: Change for your target branch, or include branches you wish to trigger this workflow file.
      - main
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "smartramanan" ## Name of your existing Terraform Cloud Organization. RECOMMENDED: use repository variables. ex. "${{ vars.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TERRAFORM_CLOUD_TOKEN }}" ## Terraform Cloud API Token. RECOMMENDED: replace with github action secrets. ex. "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "aws_gitaction" ## Name of your existing workspace in Terraform Cloud.
  CONFIG_DIRECTORY: 'module/' ## Directory of your Terraform Configuration. Relative to the project root.

jobs:
  terraform-cloud-speculative-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          
#       - uses: hashicorp/tfc-workflows-github/actions/discard-run@v1.0.0
#         id: discard
#         with:
#           token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }} # recommend to store as repository secret
#           run: ${{ steps.run.outputs.run_id }}
#           comment: "Discarded from GitHub Actions CI"

      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        id: apply
#         continue-on-error: true
        if: ${{ fromJSON(steps.run.outputs.payload).data.attributes.actions.IsConfirmable }}
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
