name: Tfsec PR Bot

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tfsec-pr-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Tfsec
      run: |
        curl -Lso tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
        chmod +x tfsec
        sudo mv tfsec /usr/local/bin/
    - name: Run Tfsec
      run: |
        tfsec --format=json ./ | tee tfsec-results.json
    - name: Add Tfsec Review
      uses: Wizer-AI/tfsec-pr-bot@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: tfsec-results.json
